/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib */

#ifndef _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
#define _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfopen
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfplay
  (JNIEnv *, jclass);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfpause
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfpause
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfseek
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfseek
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfstop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfstop
  (JNIEnv *, jclass);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib
 * Method:    sexypsfputaudiodata
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_SexypsfPlayerLib_sexypsfputaudiodata
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
