/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo */

#ifndef _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo
#define _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo
 * Method:    getFileInfo
 * Signature: (Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo_getFileInfo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMETrackInfo_getLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
