/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib */

#ifndef _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
#define _Included_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    init
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_init
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getTime
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getSample
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getSample
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    cleanup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getSampleRate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getSampleRate
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    startTrack
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_startTrack
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getTrack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getTrack
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getChannel
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getChannelNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getChannelNames
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    seek
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_seek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    skip
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_skip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    isTrackEnded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_isTrackEnded
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    setFade
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_setFade
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    setIgnoreSilence
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_setIgnoreSilence
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    getCurrentTrackInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_getCurrentTrackInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    setTempo
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_setTempo
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    muteChannel
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_muteChannel
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    muteChannels
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_muteChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    setGain
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_setGain
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib
 * Method:    setEqualizer
 * Signature: (DJ)V
 */
JNIEXPORT void JNICALL Java_com_biggo_AndroidGMEPlayer_PlayerLibs_GMEPlayerLib_setEqualizer
  (JNIEnv *, jobject, jdouble, jlong);

#ifdef __cplusplus
}
#endif
#endif
